name: continuous integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: oven-sh/setup-bun@v2
      - run: uv run pre-commit run --all-files
      - run: uv run main.py
      - run: bun install --frozen-lockfile
      - run: bun run sources
      - run: bun run build:strict
